### ISSUE TITLE
Help maintaining project

### ISSUE THREAD

**Issue by lvignals** [larics/nao-ocr#2]
Hello! For a project at work I would like to re-use and build upon the work you have done already regarding Tesseract and NAO, so I am interested in helping with the maintenance of that project but I would also need some help getting started and setup especially with the doc which is available in Croatian from what I see. Have you done any video recording available on the web related to that project? Thank you. I had no other way to contact you directly on Github so creating an issue on the project repo itself seemed like the most direct way. I hope you won't mind. Easiest way to get hold of me is via linkedin dot com  forward-slash  in  forward-slash  ludovicv

**Comment by fpetric** [comment]
Hi! 
Thank you for your interest, I took some time and made some changes to the repo organization. I also updated the instructions in the readme, so it should be easier for you to set things up at your end. Basically, you can have this running as a remote module pretty fast, if you have qibuild stuff setup, just clone in your worktree, install dependencies and build (tested few minutes ago on Ubuntu 16.04, qibuild 3.11, gcc 4.8, OpenCV 2.4.9, tesseract 3.04.01-4, leptonica 1.73-1)
As for the local installation on the robot, we did this for the older version of naoqi (v1.14), and since then we updated our NAOs but did not have time to test the procedure for the installation on the robot with new version of OS. Maybe we can work on that together.

**Comment by lvignals** [comment]
Hi Frano, I got OpenCV 2.4.9 and tesseract 3.04.01 installed, I executed tesseract on test image and it works fine I get some text on Ubuntu. I started from a fresh Ubuntu 16.04 VM so I also needed to install qiBuild tools but I am getting some error at compile time with qiBuild on the C++ sample sayhelloworld. I have gcc-4.8 loaded but it needs to be invoked directly. If using just gcc then version is 5.4, do you have gcc 4.8 setup as your default gcc on your machine or do you invoke it as gcc-4.8 wherever needed? I am wondering if qiBuild can build sayHelloWorld with gcc-5.4 so here is my question: Is using gcc 4.8 a constraint because of Tesseract or because of qiBuild? If because of qiBuild then I should prbably set gcc-4.8 as the default gcc. Any thoughts on that? Basically I would like to make sure qiBuild toolchain works properly before attempting to build NAO-OCR...

**Comment by lvignals** [comment]
Here is the error reported:
collect2: error: ld returned 1 exit status
CMakeFiles/sayhelloworld.dir/build.make:113: recipe for target 'sdk/bin/sayhelloworld' failed
make[2]: *** [sdk/bin/sayhelloworld] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/sayhelloworld.dir/all' failed
make[1]: *** [CMakeFiles/sayhelloworld.dir/all] Error 2
Makefile:116: recipe for target 'all' failed
make: *** [all] Error 2
[ERROR]: BuildFailed Error occurred when building project sayhelloworld
lvignals@ubuntu14vm:~/Development/NAOStuff/qiBuildProjects/SDK/naoqi-sdk-2.1.4.13-linux64/doc/dev/cpp/examples/core/sayhelloworld$

**Comment by fpetric** [comment]
I think the problem is in the qibuild, from my experience it does not go well with gcc 5.4 (which is default on 16.04 LTS), although the error you are getting is not familiar to me. 
I have gcc 4.8 installed alongside 5.4 and am using update-alternatives to switch between different gcc versions. This is how I did it:
`sudo apt install gcc-4.8 g++-4.8`
To set update-alternatives up, use the following commands:
`sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 100 --slave /usr/bin/g++ g++ /usr/bin/g++-4.8`
`sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 50 --slave /usr/bin/g++ g++ /usr/bin/g++-5`
which will couple gcc and g++ together. To switch between different version of the compiler, use:
`sudo update-alternatives --config gcc`

There is also an option to set the desired compiler through CMakeLists.txt:
`set( CMAKE_C_COMPILER "/usr/bin/gcc-4.8" )`
`set( CMAKE_CXX_COMPILER "/usr/bin/g++-4.8" )`
but community guidelines are strongly against that.

**Comment by lvignals** [comment]
Hi Frano, 

I solved the qibuild issue I was having. 
The problem came from the fact that I configured the build tool-chain before pointing gcc at gcc-4.8.
I was under the impression that downgrading to gcc-4.8 was a constraint of tesseract or leptonica
It seems it is qi SDK that does not like gcc 5.x. 
My plan was to test the qibuild tools before having both gcc versions setup and then downgrade the default gcc to gcc-4.8 before doing the setup of tesseract and leptonica, when in fact I should have made the switch right away. 

I think you should add a note about that in the project README. 

OpenCV and Tesseract are both running as executable on the VM. 
Tomorrow I will look into getting all the source files for OpenCV, Tesseract and Leptonica on the VM, and if time allows I will clone NAO-OCR repo and give the compilation a first try. 

It is really a shame that Github does not allow private personal messages on GitHub.
I tried to invite you by name on LinkedIn but LinkedIn required a direct email for that. If you would like you can send me a Facebook invite simply by looking me up by name Ludovic Vignals 

Thank you.
[http://image-store.slidesharecdn.com/09b0742c-1555-4c81-a117-4834df5b517b-original.png](http://image-store.slidesharecdn.com/09b0742c-1555-4c81-a117-4834df5b517b-original.png)

**Comment by lvignals** [comment]
Just saw your update now, after refreshing the page, seems our messages crossed each other. Thanks for the clarifications on using update-alternatives. Very helpful. I am am signing out, I will test the rest tomorrow. Thank you.

**Comment by lvignals** [comment]
Closing the Issue/Thread now that we made contact by email.
